@extends('layouts.global')
@section('content')
 @include('components.navadmin')
 @include('components.home')
 @include('components.category')
 @include('components.menu')
 @include('components.review')
 @include('components.footer')
@endsection
