@extends('layouts.global')
@section('content')
 @include('components.navuser')
 @include('components.home')
 @include('components.category')
 @include('components.menuuser')
 @include('components.review')
 @include('components.footer')
@endsection
